### ISSUE TITLE
Not about your blog, but your website

### ISSUE THREAD

**Issue by eldrgeek** [DSchau/blog#11]
Hey Dustin,
Tried to send this (minus this para) to you via your personal site, but the SEND button gives no evidence that it is working, so that's another problem on the site.

Found one of your Gatsby related posts and followed it until I got to your site. I think there are a lot of cool ideas, but in my browser (Chrome on Chromebook) the text below the "My Skills" images is nearly impossible to read. Even highlighting it does no good. You might want to fix that.

I think your animated headline is really cool. I sat there waiting for the net thing to come up before I concluded "OK, this guy does it all and is very creative."

Regards
Mike

PS when you fix it, if you want me to take a look, happy to

**Comment by DSchau** [comment]
Hi @eldrgeek the actual source for my website is also available, [@dschau/website](https://github.com/DSchau/website).

I just sent an e-mail to myself from the site, and didn't experience any issues. Could you explain what you're running into?

**Comment by eldrgeek** [comment]
​​
Scroll to "Want to get in touch" section.
Enter my name: Mike Wolf and email mw@mike-wolf.com
Enter a message:
Hi Dustin,
Trying from a different machine. Kubuntu, with Chrome. Let's see if this
email goes out.

Hover over Send. It highlights, showing it is active. I click. Nada.

I tried it from FFox with a one-line message . It worked.

Tried again. No good.

Tried from FFox with a different email address and a longer message.

Worked the first time. Not afterward.

Mike

**Comment by DSchau** [comment]
@eldrgeek sorry about that, that's super interesting! I will take a look when I can and see if I can address this!

The form itself is pretty vanilla JavaScript, so it's surprising that doesn't work!

**Comment by DSchau** [comment]
@eldrgeek also thank you again for reporting, and reproducing. It's appreciated!

**Comment by eldrgeek** [comment]
Are you going to fix it? Just checked and not working on Chrome. Also,
don't forget the combo of background and font color.
M

**Comment by DSchau** [comment]
I just used BrowserStack to validate Firefox 55 and then Internet Explorer. The JavaScript I'm using on that form is pretty minimal, so I think it's unlikely it's anything on my end.

Could you try in a browser without extensions, or in incognito mode or something? My guess is something could be clashing.

Also if you have browser versions (i.e. Firefox 45), that would be helpful too.

**Comment by DSchau** [comment]
@eldrgeek as info, I'm getting these e-mails :)

**Comment by eldrgeek** [comment]
Yes, but are you getting the ones that did not go? :)

I sent one out last night from an Incognito window.

Then I tried turning off all my plugins -- which AFAIK did not send an email

What finally worked was reloading after removing all the plugins. Then one
went out.

I'm now adding the plugins a couple at a time to see what fails.

I am assuming when I saw "Sending...." that it went, and when I did not,
then it did not go.

When I get one that does not go, I will send a second that says "THIS DID
NOT SEND" If you ever see such an email, let me know right away

Mike

**Comment by DSchau** [comment]
I got a bunch of e-mails last night too. Why exactly do you think they're not working? If you see the success message animate in, they were sent to me!

I'm only concerned if you're not seeing that success message after sending the e-mail.

**Comment by eldrgeek** [comment]
Right. Right now they are going. I need to get back to a condition where
they are not being sent, and then send you a message that says "YOU SHOULD
NOT SEE THIS" or some such.

**Comment by DSchau** [comment]
OK sounds good! I will probably close this until we have concrete reproduction steps, or you realize something was wrong on your end (I'd like to know what happened).

That work?

**Comment by eldrgeek** [comment]
Works for me. Until you get an email that says "YOU SHOULD NOT SEE THIS"
it's non-reproducible.

**Comment by DSchau** [comment]
Thanks for helping :) Good luck!

I'll e-mail you/reply to this ticket if I ever get one

**Comment by DSchau** [comment]
@eldrgeek I found an issue (and fixed it), but not _sure_ if it was what you were encountering.

Could it have been multi-line entries? I relaxed the validation (so that any message >= 1 characters passes). I think this might have been what you were running into?

**Comment by eldrgeek** [comment]
Might have been. I may not have been consistent in my testing and maybe
that led to false positives. Right now I have half my plugins enabled. I'll
keep checking from time to time as continue to enable them and I will let
you know if there are any problems

Mike

**Comment by DSchau** [comment]
Got your e-mail btw too!

**Comment by DSchau** [comment]
@eldrgeek I also open sourced the template I made :) https://github.com/dschau/email-template

As well as the AWS Lamda function -> https://github.com/dschau/email-handler
