### ISSUE TITLE
GraphQL query failure

### ISSUE THREAD

**Issue by bencodezen** [DSchau/blog#5]
Hey Dustin! 

First off, wanted to thank you for taking the time to write your blog post on getting a Gatsby blog setup. It was helpful to have some sort of path to creating something working.

Got a question for you though:

```js
query BlogPostByPath($path: String!) {
  ...
}
```

When I put this query inside the graphql debugger, it was returning an error for me because it couldn't find $path. However, when I removed the `!` it worked. 

```js
query BlogPostByPath($path: String) {
  ...
}
```

Could you explain why there is a `!` there?

**Comment by DSchau** [comment]
That could very well be a bug! Nice catch!

**Comment by DSchau** [comment]
(I am not a GraphQL pro by any means)

**Comment by DSchau** [comment]
So looks like the `!` makes the field non-nullable, which actually makes sense in this context.

We can't query a blog post without a path!

I learned that from [this article](http://graphql.org/graphql-js/passing-arguments/), particularly this snippet

> The exclamation point in Int! indicates that numDice can't be null, which means we can skip a bit of validation logic to make our server code simpler. We can let numSides be null and assume that by default a die has 6 sides.

Thank you for taking the time to say thank you. Means a lot, and glad it's appreciated!

**Comment by DSchau** [comment]
@bencodezen and then as far as using the debugger (assuming you mean GraphiQL?), this worked for me!

![screen shot 2017-08-28 at 11 23 32 am](https://user-images.githubusercontent.com/3924690/29782742-5b7990f6-8be3-11e7-8d8d-928aa27bc58c.png)

**Comment by bencodezen** [comment]
@DSchau Ah. I think I see what happened. You provided a Query Variable in the debugger. I didn't even see that section when I was using the debugger. I just assumed that it would actually query the file system instead of depending on the variable. 

Thanks for the response!

**Comment by DSchau** [comment]
No problem!
